version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: "monday"
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - 1.20.0
    - 1.20.1
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: ipython
    versions:
    - 7.19.0
    - 7.20.0
